name: deploy

on:
    push:
        branches:
            - main

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1.2.0

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1.6.0

            - name: Login to Docker Registry
              uses: docker/login-action@v1.14.1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASS }}

            - name: Build and push Docker images
              uses: docker/build-push-action@v2.10.0
              id: docker_build
              with:
                  push: true
                  tags: activedev007/url-shortener:latest
