name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.4.2

            - name: Use Node.js 16.3
              uses: actions/setup-node@v3.1.1
              with:
                  node-version: '16.3.0'
                  cache: 'npm'

            - run: npm ci
            - run: npm run build --if-present
            - run: npm run test
